default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>

development:
  <<: *default
  channel_prefix: workspace_development

test:
  <<: *default
  channel_prefix: workspace_test

production:
  <<: *default
  channel_prefix: workspace_production
