inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/bundle'
Style:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
