FROM node:20

ENV LANG C.UTF-8
RUN apt-get update -qq && apt-get install -y \
  build-essential graphviz curl vim jq dnsutils \
  && rm -rf /var/lib/apt/lists/*

RUN \
  echo "PS1='🐳  \[\033[1;36m\][\$(hostname)] \[\033[1;34m\]\W\[\033[0;35m\] \[\033[1;36m\]\[\033[0m\]'" >> ~/.bashrc; \
  echo "alias ls='ls --color=auto'" >> ~/.bashrc; \
  echo "alias grep='grep --color=auto'" >> ~/.bashrc

ENV EDITOR=vim
WORKDIR /workspace

CMD ["/bin/sh"]
